[mypy]
check_untyped_defs = True
disallow_any_decorated = True
; disallow_any_explicit = True
; disallow_any_expr = True
disallow_any_generics = True
; disallow_any_unimported = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_untyped_defs = True
no_implicit_optional = True
python_version = 3.7
strict_equality = True
strict_optional = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True

[mypy-flask_socketio]
ignore_missing_imports = True

[mypy-gpiozero]
ignore_missing_imports = True

[mypy-transitions]
ignore_missing_imports = True

[mypy-transitions.extensions]
ignore_missing_imports = True

[mypy-transitions.extensions.states]
ignore_missing_imports = True

[mypy-watchdog.events]
ignore_missing_imports = True

[mypy-watchdog.observers]
ignore_missing_imports = True
